### ISSUE TITLE
Remove meal cancellation feature from mess fragment

### ISSUE THREAD

**Issue by amangrobo** [NJACKWinterOfCode/IITP-App#1]
Currently, the meal cancellation feature is present.

<img height=400px src='https://user-images.githubusercontent.com/34675420/70058435-e839be00-1604-11ea-8b6f-64efa91c134f.jpg'/>

**Comment by rajkumaar23** [comment]
So, `Your Cancelled Meals` button should also be removed ?

**Comment by amangrobo** [comment]
yah
