### ISSUE TITLE
Add reset password feature

### ISSUE THREAD

**Issue by amangrobo** [NJACKWinterOfCode/IITP-App#10]
Add reset password fragment and design its layout. Ask for the email of the user only. You don't have to design the api part.

**Comment by pavitrawalia** [comment]
@amangrobo can i take up this issue ?

**Comment by amangrobo** [comment]
> @amangrobo can i take up this issue ?

yah sure

**Comment by pavitrawalia** [comment]
please assign me the issue so that i can start working on it.

**Comment by amangrobo** [comment]
@pavitrawalia updates??

**Comment by pavitrawalia** [comment]
@amangrobo Working on it . Will update you by EOD .

**Comment by s-ayush2903** [comment]
Now I'm going to fix this issue

**Comment by rajkumaar23** [comment]
@amangrobo Can I take up this issue since it has been pending for long ? If yes, please assign me.
