### ISSUE TITLE
Hide webmail button in action bar in main activity

### ISSUE THREAD

**Issue by amangrobo** [NJACKWinterOfCode/IITP-App#3]
<img height=400px src="https://user-images.githubusercontent.com/34675420/70059298-8da16180-1606-11ea-819d-fddadbc1cc36.jpg"/>

**Comment by niteshnanda02** [comment]
I am working on this issue, when I clone the project the JSON file is missing. How can I get it?
Or i need to add this project on firebase and  from ther get the JSON file

**Comment by amangrobo** [comment]
Create a Firebase project from your own account and connect it with the project

**Comment by niteshnanda02** [comment]
Ok sir

**Comment by niteshnanda02** [comment]
![Screenshot from 2019-12-03 21-27-13](https://user-images.githubusercontent.com/40588354/70067138-d6134c00-1613-11ea-9a38-f5509a0f0fe3.png)
 What is the value of this string "FCM_authorization". I am getting error for this

**Comment by amangrobo** [comment]
You can comment that code, or you can add a random string in string resources named FCM_authorization

**Comment by niteshnanda02** [comment]
sir how to login in the app .Whenever I enter email ,it's ask for enter a valid email

**Comment by amangrobo** [comment]
Test account: apptest@iitp.ac.in
password: test

**Comment by rajkumaar23** [comment]
@amangrobo Why isn’t my score getting updated in leaderboard ? Beginner label has 5 points right ?

**Comment by amangrobo** [comment]
Don't worry, it will be updated
