### ISSUE TITLE
Implement a feature to store FCM device registration tokens in firestore database and update it when token is refreshed

### ISSUE THREAD

**Issue by amangrobo** [NJACKWinterOfCode/IITP-App#6]
For details visit: https://firebase.google.com/docs/cloud-messaging/android/client#sample-register

**Comment by rajkumaar23** [comment]
I would like to work on this @amangrobo

**Comment by amangrobo** [comment]
Go on

**Comment by rajkumaar23** [comment]
I have few doubts.
1) Which database to use ? Firebase Database or Cloud Firestore ? (Both are available in Firebase)
2) How do you wish to track the token ? Is it based on the user's mail id ? Please explain the mapping.

**Comment by amangrobo** [comment]
1. We'll use Cloud Firestore here.
2. On the first installation of the app, we are gonna get the FCM token and save it, and onTokenRefreshed, we are gonna update it.
Database structure: 
* Collection: fcm_tokens
    * Document: USER_MONGO_ID
        * key-value pair for the token (key = fcm_token)

**Comment by rajkumaar23** [comment]
What if there's not an USER_MONGO_ID in SharedPrefs when FCM token is refreshed for the device ? In that case, can I store the token in SharedPrefs as well as set `tokenRefreshed=true` and then when the user logs in, I'll map it to his MONGO_ID ?

**Comment by amangrobo** [comment]
Store the token only after the user logs in and refresh it only if the user is logged in

**Comment by amangrobo** [comment]
A token will be mapped to the user mongo id every time a user logs in and if a token already exists for that mongo id, it will be replaced

**Comment by rajkumaar23** [comment]
Got it. 👍
