### ISSUE TITLE
Fix glitch in swipe to remove in notifications

### ISSUE THREAD

**Issue by amangrobo** [NJACKWinterOfCode/IITP-App#7]
Glitch: 
<img height=400px src="https://user-images.githubusercontent.com/34675420/70109051-caa23e00-1670-11ea-807d-94fd3d0a2c65.jpg"/>

**Comment by s-ayush2903** [comment]
@amangrobo Can you describe the method to reproduce the same glitch?

**Comment by amangrobo** [comment]
OnSwipeTouchListener in utils package is implemented and attached to the RecyclerView in NotificationsFragment
