### ISSUE TITLE
Add forgot password option in login fragment layout

### ISSUE THREAD

**Issue by amangrobo** [NJACKWinterOfCode/IITP-App#8]
Task: Implement forgot password in layout only

Current login screen:

<img height=400px src="https://user-images.githubusercontent.com/34675420/70109412-cf1b2680-1671-11ea-8f34-019266f34299.png"/>

**Comment by rajkumaar23** [comment]
I would like to work on this @amangrobo

**Comment by amangrobo** [comment]
@rajkumaar23 Go on

**Comment by rajkumaar23** [comment]
@amangrobo, What do you expect the app to display when forgot password is clicked ?

**Comment by amangrobo** [comment]
Well, that's another issue #10
